// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/dneumoin/test_vote/backend/internal/service/poll/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPollProvider is a mock of PollProvider interface.
type MockPollProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPollProviderMockRecorder
	isgomock struct{}
}

// MockPollProviderMockRecorder is the mock recorder for MockPollProvider.
type MockPollProviderMockRecorder struct {
	mock *MockPollProvider
}

// NewMockPollProvider creates a new mock instance.
func NewMockPollProvider(ctrl *gomock.Controller) *MockPollProvider {
	mock := &MockPollProvider{ctrl: ctrl}
	mock.recorder = &MockPollProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollProvider) EXPECT() *MockPollProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPollProvider) Get(ctx context.Context, pollID uuid.UUID) (dto.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pollID)
	ret0, _ := ret[0].(dto.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPollProviderMockRecorder) Get(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPollProvider)(nil).Get), ctx, pollID)
}

// MockMarker is a mock of Marker interface.
type MockMarker struct {
	ctrl     *gomock.Controller
	recorder *MockMarkerMockRecorder
	isgomock struct{}
}

// MockMarkerMockRecorder is the mock recorder for MockMarker.
type MockMarkerMockRecorder struct {
	mock *MockMarker
}

// NewMockMarker creates a new mock instance.
func NewMockMarker(ctrl *gomock.Controller) *MockMarker {
	mock := &MockMarker{ctrl: ctrl}
	mock.recorder = &MockMarkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarker) EXPECT() *MockMarkerMockRecorder {
	return m.recorder
}

// MarkVoted mocks base method.
func (m *MockMarker) MarkVoted(ctx context.Context, key string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVoted", ctx, key, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkVoted indicates an expected call of MarkVoted.
func (mr *MockMarkerMockRecorder) MarkVoted(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVoted", reflect.TypeOf((*MockMarker)(nil).MarkVoted), ctx, key, ttl)
}
