// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source=worker.go -destination=mocks/worker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	counters "github.com/dneumoin/test_vote/backend/internal/counters"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPollLister is a mock of PollLister interface.
type MockPollLister struct {
	ctrl     *gomock.Controller
	recorder *MockPollListerMockRecorder
	isgomock struct{}
}

// MockPollListerMockRecorder is the mock recorder for MockPollLister.
type MockPollListerMockRecorder struct {
	mock *MockPollLister
}

// NewMockPollLister creates a new mock instance.
func NewMockPollLister(ctrl *gomock.Controller) *MockPollLister {
	mock := &MockPollLister{ctrl: ctrl}
	mock.recorder = &MockPollListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollLister) EXPECT() *MockPollListerMockRecorder {
	return m.recorder
}

// ListForSnapshot mocks base method.
func (m *MockPollLister) ListForSnapshot(ctx context.Context, closedGrace time.Duration) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForSnapshot", ctx, closedGrace)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForSnapshot indicates an expected call of ListForSnapshot.
func (mr *MockPollListerMockRecorder) ListForSnapshot(ctx, closedGrace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForSnapshot", reflect.TypeOf((*MockPollLister)(nil).ListForSnapshot), ctx, closedGrace)
}

// MockLiveCounters is a mock of LiveCounters interface.
type MockLiveCounters struct {
	ctrl     *gomock.Controller
	recorder *MockLiveCountersMockRecorder
	isgomock struct{}
}

// MockLiveCountersMockRecorder is the mock recorder for MockLiveCounters.
type MockLiveCountersMockRecorder struct {
	mock *MockLiveCounters
}

// NewMockLiveCounters creates a new mock instance.
func NewMockLiveCounters(ctrl *gomock.Controller) *MockLiveCounters {
	mock := &MockLiveCounters{ctrl: ctrl}
	mock.recorder = &MockLiveCountersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveCounters) EXPECT() *MockLiveCountersMockRecorder {
	return m.recorder
}

// ReadCounts mocks base method.
func (m *MockLiveCounters) ReadCounts(ctx context.Context, pollID uuid.UUID) (counters.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCounts", ctx, pollID)
	ret0, _ := ret[0].(counters.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCounts indicates an expected call of ReadCounts.
func (mr *MockLiveCountersMockRecorder) ReadCounts(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCounts", reflect.TypeOf((*MockLiveCounters)(nil).ReadCounts), ctx, pollID)
}

// MockResultsStorage is a mock of ResultsStorage interface.
type MockResultsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockResultsStorageMockRecorder
	isgomock struct{}
}

// MockResultsStorageMockRecorder is the mock recorder for MockResultsStorage.
type MockResultsStorageMockRecorder struct {
	mock *MockResultsStorage
}

// NewMockResultsStorage creates a new mock instance.
func NewMockResultsStorage(ctrl *gomock.Controller) *MockResultsStorage {
	mock := &MockResultsStorage{ctrl: ctrl}
	mock.recorder = &MockResultsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultsStorage) EXPECT() *MockResultsStorageMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockResultsStorage) Save(ctx context.Context, pollID uuid.UUID, voters int64, counts map[uuid.UUID]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, pollID, voters, counts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockResultsStorageMockRecorder) Save(ctx, pollID, voters, counts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockResultsStorage)(nil).Save), ctx, pollID, voters, counts)
}
